### ISSUE TITLE
Which HISE, JUCE versions to use?

### ISSUE THREAD

**Issue by martinfinke** [christophhart/streaming_example#2]
Which HISE commit and JUCE version should be used to compile this example? On my system, I get compile errors, e.g. "No type named 'NewSampleThreadPool'".

Also, the copyright info at the top of this file is not commented out:
https://github.com/christophhart/streaming_example/blob/7ab1c9f796be46d119ff0f617ae7020fd4207c7b/StreamingDemoPlugin/Source/StreamingExample.cpp#L1

**Comment by christoph-hart** [comment]
Oops, don't know how that slipped in, but it's fixed now.

I also fixed a name clash that came from refactoring: the NewSampleThreadPool isn't that new anymore, so it's just SampleThreadPool now :)

Now you should be able to build the project using the latest HISE code and the current JUCE codebase (the master branch), but it might also run with the development branch.

**Comment by martinfinke** [comment]
Thanks, works fine now!
